# execute, no pdf
name: MyST GitHub Pages Deploy
on:
  workflow_call:

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    env:
      TYPST_FONT_PATHS: ${{ github.workspace }}/typst_template/src/assets/fonts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install MyST
        run: npm install -g mystmd

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'   # or your version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install jupyter-server nbclient nbformat ipykernel jupyter-client ipython
          pip install matplotlib numpy pandas scipy plotly ipywidgets
          python -m ipykernel install --user --name=python3


      - name: Check labels
        run: |
          python .jb-workflows/check.py    
          
      - name: Build HTML Assets
        run: myst build --html --execute

      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5