# .github/workflows/myst-pages.yml

name: Build and deploy MyST site

on:
  workflow_call:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install MyST Markdown
        run: npm install -g mystmd

      - name: Check labels
        run: |
          python check.py    

      - name: Build HTML
        env:
          BASE_URL: /${{ github.event.repository.name }}
        run: myst build --html --debug

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5